autoload -Uz compinit promptinit add-zsh-hook

export ZSH_CONFIG_DIR=~/.config/zsh

source $ZSH_CONFIG_DIR/constants.sh
source $ZSH_CONFIG_DIR/path.sh
source $ZSH_CONFIG_DIR/prompt.sh
source $ZSH_CONFIG_DIR/aliases.sh
source $ZSH_CONFIG_DIR/bsd-style-pkg.sh
source $ZSH_CONFIG_DIR/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

if [[ -e $ZSH_CONFIG_DIR/local.sh ]]; then
    source $ZSH_CONFIG_DIR/local.sh
fi

# initialization
compinit
promptinit

# append space to the end of command before pipe
export ZLE_SPACE_SUFFIX_CHARS=$'|&'

# enable history
export HISTFILE="$HOME/.zsh_history"
export HISTSIZE=10000
export SAVEHIST=10000

# shell-side configuration for emacs's vterm to correctly track the directory
if [[ "$INSIDE_EMACS" = 'vterm' ]]; then
    source $ZSH_CONFIG_DIR/vterm.sh
fi
