""" Vim 8 / Neovim configuration section
set shiftwidth=4 tabstop=4
set nu rnu							  " 'hybrid' line numbers
set t_Co=256						  " truecolor
set scrolloff=10					  " scroll padding
filetype plugin indent on
call matchadd('ColorColumn', '\%80v', 100)	" highlight column 80

""" Plugin listing section
call plug#begin('~/.vim/plugged')
	Plug 'w0rp/ale'
	Plug 'tpope/vim-surround'
	Plug 'scrooloose/nerdcommenter'
	Plug 'itchyny/lightline.vim'
call plug#end()

" lightline config
set laststatus=2
let g:lightline = {
	\ 'colorscheme': 'seoul256',
	\ }
set noshowmode
