#!/bin/bash

# Ensure user install dir exists and has subdirs we expect
USER_LOCAL="$HOME/.local"
if [[ ! -d "$USER_LOCAL" ]]; then
	mkdir -p "$USER_LOCAL"
fi
if [[ ! -d "$USER_LOCAL/bin" ]]; then
    mkdir "$USER_LOCAL/bin"
fi
if [[ ! -d "$USER_LOCAL/lib" ]]; then
    mkdir "$USER_LOCAL/lib"
fi
if [[ ! -d "$USER_LOCAL/include" ]]; then
    mkdir "$USER_LOCAL/include"
fi
if [[ ! -d "$USER_LOCAL/share" ]]; then
    mkdir "$USER_LOCAL/share"
fi

# Ensure portapotty state tracking directory exists
PORTAPOTTY_TRACKING_DIR="$HOME/.local/share/portapotty"
if [[ ! -d "$PORTAPOTTY_TRACKING_DIR" ]]; then
	mkdir -p "$PORTAPOTTY_TRACKING_DIR"
fi

# Create new 'push-up' script for portapotty
PUSH_UP="$USER_LOCAL/bin/push-up"
cat >> "$PUSH_UP" << EOF
#!/bin/bash
# This script was generated by portapotty, to push all changes to local
# dotfiles to the user's local copy of the portapotty repo
EOF
chmod u+x "$PUSH_UP"

# Update package listing
sudo apt update
