#!/bin/bash

# Ensure user bin exists
USER_BIN="$HOME/.local/bin"
if [[ ! -d "$USER_BIN" ]]; then
	mkdir -p "$USER_BIN"
fi

# Ensure portapotty state tracking directory exists
PORTAPOTTY_TRACKING_DIR="$HOME/.local/share/portapotty"
if [[ ! -d "$PORTAPOTTY_TRACKING_DIR" ]]; then
	mkdir -p "$PORTAPOTTY_TRACKING_DIR"
fi

# Create new 'push' script for portapotty
PORTAPUSH="$HOME/.local/portapush"
cat >> "$PORTAPUSH" << EOF
#!/bin/bash
# This script was generated by portapotty, to push all changes to local
# dotfiles to the user's local copy of the portapotty repo
EOF
chmod u+x "$PORTAPUSH"

# Update package listing
sudo apt update
