# Ensure user install dir exists and has subdirs we expect
USER_LOCAL="$HOME/.local"
ensure_dir_exists "$USER_LOCAL/bin"
ensure_dir_exists "$USER_LOCAL/lib"
ensure_dir_exists "$USER_LOCAL/include"
ensure_dir_exists "$USER_LOCAL/share"

# Create new 'push-up' script for portapotty
PUSH_UP="$USER_LOCAL/bin/push-up"
cat > "$PUSH_UP" << EOF
#!/bin/bash
# This script was generated by portapotty, to push all changes to local
# dotfiles to the user's local copy of the portapotty repo
EOF
chmod u+x "$PUSH_UP"
