# -*- mode: sh -*-
autoload -Uz compinit promptinit add-zsh-hook

export ZSH_CONFIG_DIR=~/.config/zsh

source $ZSH_CONFIG_DIR/constants.sh
source $ZSH_CONFIG_DIR/path.sh
source $ZSH_CONFIG_DIR/aliases.sh
source $ZSH_CONFIG_DIR/bsd-style-pkg.sh
source $ZSH_CONFIG_DIR/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# NOTE prompt.zsh needs to be sourced after vterm.zsh for shell-side integration
# (directory tracking) to work properly
if [[ "$INSIDE_EMACS" = 'vterm' ]]; then
    source $ZSH_CONFIG_DIR/vterm.zsh
fi
source $ZSH_CONFIG_DIR/prompt.zsh

if [[ -e $ZSH_CONFIG_DIR/local.sh ]]; then
    source $ZSH_CONFIG_DIR/local.sh
fi

# initialization
compinit
promptinit

# append space to the end of command before pipe
export ZLE_SPACE_SUFFIX_CHARS=$'|&'

# enable history
export HISTFILE="$HOME/.zsh_history"
export HISTSIZE=10000
export SAVEHIST=10000
